### ISSUE TITLE
I can not find  imgs_train.npy ， where is it?

### ISSUE THREAD

**Issue by FrankieTong89** [yihui-he/u-net#16]
When I download this project, run "data.py", it warning said "No such file or directory: 'imgs_train.npy'", 
How can I obtain this file?  Thank you very much

**Comment by ethanhe42** [comment]
https://github.com/yihui-he/u-net/blob/d7a1de97f0f4dfa52ddf0262c1c78a1d162ddbc1/data.py#L58
