### ISSUE TITLE
About dice loss

### ISSUE THREAD

**Issue by sagarhukkire** [yihui-he/u-net#2]
Hi
I am using dice loss in my network for batch size 1. sometimes loss is crossing 1 as  I am using just same type code but  different terminology but basic is same 
(2. * intersection + smooth) / (K.sum(y_true_f*y_true_f) + K.sum(y_pred_f*y_pred_f) + smooth)

But what is meaning of below code which I found in your network ,does it normalize and how to understand it.
**I mean if Dice loss top is 0.9 and bottom is 0.9 then sum is 1.8 and below equation will give -0.8**
def dice_coef_loss(y_true, y_pred):
    return 1.-dice_coef(y_true, y_pred)
Thanks

**Comment by ethanhe42** [comment]
@sagarax009 I'm not quite clear about your question. For this piece of code, it compute loss with the dice coefficient function which is already defined.
