### ISSUE TITLE
A problem about loading data

### ISSUE THREAD

**Issue by lowkeygit** [yihui-he/u-net#8]
I got an Error when I try to run data.py. 

When running the create_train_data() function, it returns:
 imgs = np.ndarray((total, 1, image_rows, image_cols), dtype=np.uint8)
TypeError: 'float' object cannot be interpreted as an integer

How to fix this problem?

Thanks a lot.

**Comment by ethanhe42** [comment]
try int(total)

**Comment by lowkeygit** [comment]
@yihui-he 
Thank you for your reply. It helps.
