### ISSUE TITLE
How to generate hdf5 file?

### ISSUE THREAD

**Issue by lowkeygit** [yihui-he/u-net#9]
Q1: How to generate the hdf5 file in order to save the parameters and models?

    print('-'*30)
    print('Loading saved weights...')
    print('-'*30)
    model.load_weights('unet.hdf5')

I found this part. Don't know how to get this file. 

Q2: How to print out the result?
After running the train.py, I got "imgs_mask_test.npy".
Only shows me:  5508/5508 [==============================] - 271s   
How to print out the result, such as dice coefficient?
Can I just add a line " print(dice_coef)" inside train_and_predict()?

Hope to give me some advices. Thanks.

**Comment by ethanhe42** [comment]
- https://github.com/yihui-he/u-net/blob/master/train.py#L155
- I've forgot.

**Comment by lowkeygit** [comment]
The data is binary, not multiclass, right?
I'm gonna calculate the f1 score with scikit-learn.
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html

**Comment by ethanhe42** [comment]
Yes. In the competition, actually the score is computed by the organizer

**Comment by lowkeygit** [comment]
Ask one more question:
def dice_coef_loss(y_true, y_pred):
    return 1.-dice_coef(y_true, y_pred)

In this function, y_true and y_pred are 2 parameters. And then you call this function inside def get_unet(). Where those parameters come from?

btw, I try to print out dice and f1 score, but get this result.
<function dice_coef at 0x1183288c8>
<function dice_coef_loss at 0x11f9adc80>
<function f1score at 0x11fe596a8>
I don't think it's correct.... how to print out?
